### ISSUE TITLE
Music bot stopped working

### ISSUE THREAD

**Issue by RokiNoki** [ericyoondotcom/MinecraftManhunt#74]
The music bot seems to have stopped working, it keeps reconnecting and does not output any sound. After some research, it appears to be happening due to a change in the Discord API.

**Comment by ericyoondotcom** [comment]
Thanks for reporting this issue. I'll take a look next week.

**Comment by happyjoanna8** [comment]
> Thanks for reporting this issue. I'll take a look next week.

Have you been able to fix this yet? It's still an issue (for me at least) It's alright if you have been busy or unable to get started on fixing it. Please fix it when you can though! It will be much appreciated :)

**Comment by ericyoondotcom** [comment]
@RokiNoki @happyjoanna8 I'm glad to say that I've found time to work on this issue. Please download [latest release 1.4.1](https://github.com/ericyoondotcom/MinecraftManhunt/releases/tag/v1.4.1) and check it out—let me know if you experience any more bugs after upgrading.
